### ISSUE TITLE
Package depthImage to LaserScan

### ISSUE THREAD

**Issue by EduardoQD** [RNorlie/MyFirstSLAM#1]
Hello, 

I would like to ask you about the package DepthImage to Laser Scan, because I'm trying to install in my ros2 foxy environment and I have some fails during the colcon build. For this reason I ask you becuase I've seen other branch that you use it.

**Comment by RNorlie** [comment]
@EduardoQD ,

I had a similar issue where the node would crash whenever I launched any other ROS node alongside it. Did you install the package from source or using a package manager?

I had issues with the source foxy-devel version, but when I installed it with `sudo apt install ros-foxy-depthimage-to-laserscan`, everything worked fine. I was running ubuntu 20.04 on a Jetson Xavier NX.

**Comment by EduardoQD** [comment]
Hello @RNorlie ,
I've download the zip, and to unzip the folders. Tomorrow I'm going to install with this command.

Maybe I have the same problem for not use a package manager
